//----------------------------------------------
//
//        Sketch Generated by Visuino
//              www.visuino.com
//          Version  7.8.2.246
//
//------------------ Source --------------------
//
// CubeRemake.owarduino
//
//----------------------------------------------

#define VISUINO_ARDUINO_NANO
#define _MITOV_DISPLAY_SSD1306_I2C

#include <OpenWire.h>
#include <Mitov.h>
#include <Mitov_FormattedSerial.h>
#include <Wire.h>
#include <Mitov_Basic_I2C.h>
#include <Mitov_Display_SSD1306_I2C.h>
#include <GraphicsFont5x7.h>

// Arduino Board Declarations

namespace BoardDeclarations
{
Mitov::ArduinoAnalogInputChannel<0> ArduinoAnalogInputChannel_0;
} // BoardDeclarations

// Declarations

namespace Declarations
{
Mitov::DisplaySSD1306<Mitov::DisplaySSD1306NoReset<Mitov::Display_odtSSD1306_I2C<0x12,60,128,64,TwoWire,Wire>>, 128, 64> DisplayOLED1 = Mitov::DisplaySSD1306<Mitov::DisplaySSD1306NoReset<Mitov::Display_odtSSD1306_I2C<0x12,60,128,64,TwoWire,Wire>>, 128, 64>( Mitov::GraphicsFont5x7 );
Mitov::ArduinoSerialInput<Mitov::DisplaySSD1306<Mitov::DisplaySSD1306NoReset<Mitov::Display_odtSSD1306_I2C<0x12,60,128,64,TwoWire,Wire>>, 128, 64>, Declarations::DisplayOLED1, float> DisplayOLED1_InputFloat_1;
} // Declarations

// Pin Call Declarations

namespace PinCalls
{
void PinCallerReceive1( void *_Data );
} // PinCalls

// Pin Call Implementations

namespace PinCalls
{
void PinCallerReceive1( void *_Data )
{
  Declarations::DisplayOLED1_InputFloat_1.InputPin_o_Receive( _Data );
}

} // PinCalls

namespace ComponentsHardware
{
void SystemUpdateHardware()
{
}
} // ComponentsHardware

//The setup function is called once at startup of the sketch
void setup()
{
  Wire.begin();
  BoardDeclarations::ArduinoAnalogInputChannel_0.OutputPin.SetCallback( PinCalls::PinCallerReceive1 );

  BoardDeclarations::ArduinoAnalogInputChannel_0.SystemInit();
  Declarations::DisplayOLED1.SystemInit();

  BoardDeclarations::ArduinoAnalogInputChannel_0.SystemStart();
  Declarations::DisplayOLED1.SystemStart();
}

// The loop function is called in an endless loop
void loop()
{
  unsigned long A_Current_Microseconds = micros();

  BoardDeclarations::ArduinoAnalogInputChannel_0.SystemLoopBegin( A_Current_Microseconds );

  Declarations::DisplayOLED1.SystemLoopEnd( A_Current_Microseconds );
}
